# Adapted from https://github.com/actions/starter-workflows/blob/master/ci/gradle-publish.yml
# This workflow will build a package using Gradle and then publish it to maven local when a release is created

name: Gradle Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    #- name: Publish to maven local
    #  run: ./gradlew publishToMavenLocal --warning-mode all
    - name: Publish to GitHub Packages
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: ./gradlew publishReleasePublicationToGitHub --warning-mode all
